# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous Integration (Python)
on: push

jobs:
  build:
    # environment: project_name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]  # Add more Python versions to test here

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Virtual Environment
      uses: actions/cache@v4
      with:
        path: |
          .venv
          ~/.cache/pip
          ~/.cache/uv
        key: ${{ runner.os }}-venv-${{ hashFiles('uv.lock') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync --all-groups

    - name: Lint with ruff
      run: uv run ruff check .
    - name: Check types with mypy
      run: uv run mypy .
    - name: Test with pytest
      run: uv run pytest .

    - name: Coveralls
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      uses: coverallsapp/github-action@v2.3.6
